const mongoose = require('mongoose');

const OrderSchema = new mongoose.Schema({
    name: { type: String, default: "" },
	phoneNumber: { type: String, default: "" },
    receivedDate: { type: String, default: null },
    returnDate: { type: String, default: null },
    numberOfSuits: { type: Number, default: 0 },
    length: { type: Number, default: 0 },
    typeOfSewing: { type: String, default: "" },
    fullShoulder: { type: String, default: "" },
    monda: { type: String, default: "" },
    bazoHalf: { type: String, default: "" },
    bazoLength: { type: String, default: "" },
    chest: { type: Number, default: 0 },
    stomach: { type: Number, default: 0 },
    ghara: { type: Number, default: 0 },
    banCollar: { type: String, default: "" },
    collarType: { type: String, default: "" },
    pentOption: { type: String, default: "" },
    shalwarGhara: { type: String, default: "" },
    poncha: { type: String, default: "" },
    asang: { type: String, default: "" },
    typeOfButton: { type: String, default: "" },
    kuff: { type: String, default: "" },
    pati: { type: String, default: "" },
    pakit: { type: String, default: "" },
    note: { type: String, default: "" },
    design: { type: String, default: "" },
    typeOfCloth: { type: String, default: "" },
    Sholder: { type: Number, default: 0 },
    BanSize: { type: Number, default: 0 },
    neckSize: { type: Number, default: 0 },
    pentLength: { type: Number, default: 0 },
    hip: { type: Number, default: 0 },
    thigh: { type: Number, default: 0 },
    bottom: { type: Number, default: 0 },
    frontRaise: { type: Number, default: 0 },
    backRaise: { type: Number, default: 0 },
    shalwarLength: { type: Number, default: 0 },
    // keys to control Data flow
    status: { type: String, required: true },
});

module.exports = mongoose.model('Order', OrderSchema);
